const getShopStory = async (shopType, race) => {
  const shopStoryLibrary = {
    "general-shop": {
      Human: [
        "You find yourself inside a quaint shop in 'Trader's Crossroads'.",
        "Sundries, trinkets, and all sorts of oddities line the shelves, catching your curious gaze.",
        "Behind the counter, a jovial shopkeeper greets you, his smile warm and inviting.",
        "'Hello there, traveler. What can I do for you today?' the shopkeeper asks, his hands resting comfortably on the counter.",
        "You shares your needs with the shopkeeper, discussing your journey and the supplies you require.",
        "After a friendly exchange, the shopkeeper helps you find what you need, their conversation filled with stories and laughter.",
        "open-general-shop",
        "After purchasing your goods, you thank the shopkeeper. 'Thank you for your service,' you say to the shopkeeper, then leave the shop, ready for the journey ahead.",
        "You look at the map and pick your next location to travel to.",
        "end",
      ],
      Dwarf: [
        "In the midst of 'Trader's Crossroads', you find yourself in a cozy shop.",
        "Surrounded by knick-knacks, baubles, and numerous curiosities, your keen dwarf eyes scan the merchandise.",
        "A surprised gasp escapes from the shopkeeper as he notices you, 'A dwarf in my shop? How exciting!',",
        "'Hello there, traveler! It's not everyday I have a dwarf in my store!' the shopkeeper exclaims, his eyes filled with genuine interest and delight.",
        "Your not used to such reactions, but decide to endulge the shopkeeper with warmly converses, sharing tales of your kind and discussing the supplies needed for your journey.",
        "The shopkeeper, thoroughly captivated by your stories, helps him gather his supplies, all the while continuing their animated chat.",
        "open-general-shop",
        "With your purchases complete, you gives the shopkeeper a hearty thank you. 'I appreciate your enthusiasm and your help,' you say, leaving the shop with a wave of your sturdy hand.",
        "You look at the map and pick your next location to travel to.",
        "end",
      ],
      Elf: [
        "In the heart of 'Trader's Crossroads' you step into a charming shop.",
        "As an elf, your keen eyes scan the shop, taking in the multitude of items ranging from the mundane to the magical.",
        "Upon noticing your elven features, the shopkeeper's expression hardens, 'An elf, huh? Not my favorite customers, but business is business.'",
        "'Greetings,' you respond, keeping your tone neutral despite the shopkeeper's apparent dislike.",
        "You state your needs and the purpose of your journey.",
        "Despite his evident disdain for elves, the shopkeeper assists you in gathering your supplies, their interaction brief and to the point.",
        "open-general-shop",
        "Having secured your purchases, you thank the shopkeeper. 'Your assistance is appreciated,' you say, leaving the shop with grace inherent to your kind.",
        "You look at the map and pick your next location to travel to.",
        "end",
      ],
    },
    "weapon-shop": {
      Human: [
        "You find yourself inside a well-kept shop in 'Verdantis'.",
        "Elegant weapons and intricate gear adorn the walls, catching your interested gaze.",
        "Behind the counter, an elven shopkeeper greets you, her demeanor calm and graceful.",
        "'Welcome, traveler. What might you be seeking today?' the shopkeeper asks, her hands resting elegantly on the counter.",
        "You share your needs with the shopkeeper, discussing your journey and the weapons you require.",
        "After a polite exchange, the shopkeeper assists you in finding what you need, the conversation laced with a bit of elven lore and wisdom.",
        "open-weapon-shop",
        "Having acquired your weapons, you thank the shopkeeper. 'Thank you for your service,' you say, leaving the shop, ready for the challenges ahead.",
        "You glance at the map and select your next destination.",
        "end",
      ],
      Dwarf: [
        "In the heart of 'Verdantis', you find yourself in a weapon shop of elven make.",
        "Weapons of the finest craftsmanship surround you, and your dwarf eyes inspect the unfamiliar designs.",
        "The elven shopkeeper notes your presence, her face contorting in clear annoyance, 'A dwarf? In my shop?'",
        "'Aye, that's right. Got a problem with it?' you retort, unfazed by the shopkeeper's apparent disdain.",
        "Despite the tension, you proceed to explain your journey and the weapons you seek.",
        "The shopkeeper, grudgingly helps you gather your weapons, their conversation terse and pointed.",
        "open-weapon-shop",
        "Once your purchases are secured, you thank the shopkeeper in your gruff manner. 'Well, it's been a...pleasure,' you say, leaving the shop with a huff.",
        "You look at the map and decide on your next stop.",
        "end",
      ],
      Elf: [
        "At 'Verdantis', you enter a shop that feels like home.",
        "The walls are adorned with weapons and gear of the highest elven craftmanship.",
        "Behind the counter, a fellow elf greets you, 'Ah, a kin in my shop. Welcome!'",
        "'Greetings,' you respond, sharing a nod of kinship with the shopkeeper.",
        "You discuss your journey and the weapons you seek with the shopkeeper.",
        "The shopkeeper assists you enthusiastically, your shared heritage making the interaction feel familiar and warm.",
        "open-weapon-shop",
        "With your purchases in hand, you express your gratitude to the shopkeeper. 'May the stars guide us,' you say, exiting the shop with a renewed sense of purpose.",
        "You study the map and select your next destination.",
        "end",
      ],
    },
    "armor-shop": {
      Human: [
        "You find yourself in a heavily fortified shop at 'Anvilorn'.",
        "Armors of different shapes and sizes, all meticulously crafted, are displayed around the shop, drawing your attention.",
        "Behind the counter, a burly dwarf grumbles as he notices you, his scowl intimidating.",
        "'What's a human doing in my shop?' he barks, clearly not thrilled by your presence.",
        "You put on a brave face and share your needs with the dwarf, discussing your journey and the armors you require.",
        "The dwarf shopkeeper, though grumpy, helps you find the necessary items, the conversation filled with grunts and terse comments.",
        "open-armor-shop",
        "After securing your armors, you thank the dwarf. 'Your help was... appreciated,' you say, exiting the shop, ready for the adventure ahead.",
        "You look at the map and pick your next destination.",
        "end",
      ],
      Dwarf: [
        "Deep in 'Anvilorn', you find yourself in a familiar setting, an armor shop of dwarf design.",
        "Your keen eyes scan the shop, admiring the sturdy dwarven armors on display.",
        "The dwarf shopkeeper greets you warmly, 'Ah, a kin in my shop! Welcome, brother!'",
        "'Good day to you, brother!' you respond, sharing the camaraderie with the shopkeeper.",
        "You engage in a friendly chat with the shopkeeper about your journey and the armors you need.",
        "The shopkeeper, eager to assist a kin, helps you gather your armors, their conversation filled with laughter and tales of the old.",
        "open-armor-shop",
        "With your purchases ready, you give the shopkeeper a hearty pat on the back. 'It's been a pleasure, brother,' you say, leaving the shop with a broad smile.",
        "You look at the map and decide on your next stop.",
        "end",
      ],
      Elf: [
        "In the heart of 'Anvilorn', you step into a dwarven armor shop.",
        "Despite the crude aesthetics by elven standards, you acknowledge the solid craftsmanship of the armors.",
        "Upon noticing your presence, the dwarf shopkeeper grunts, 'Elf, in my shop? Can't say I'm thrilled.'",
        "'Greetings,' you respond, keeping your tone neutral despite the shopkeeper's evident distaste.",
        "You calmly state your requirements and the purpose of your journey.",
        "Despite his grumpiness, the dwarf shopkeeper assists you in gathering your armor, their interaction terse and to the point.",
        "open-armor-shop",
        "Having secured your purchases, you thank the dwarf. 'Your assistance is appreciated,' you say, leaving the shop with an air of grace.",
        "You study the map and pick your next destination.",
        "end",
      ],
    },
  };
  const grabStory = shopStoryLibrary[shopType][race];
  return grabStory;
};

export default getShopStory;
