const goldenRuinsStory = [
  "The altar begins to radiate a mesmerizing golden light, illuminating the ancient ruins around you.",
  "As the glow intensifies, you dig into your satchel, recalling your recent discovery of a peculiar cubic object.",
  "Mirroring the altar, the cube emanates a warm, inviting golden radiance.",
  "With a deep breath, you gently place the cube onto the altar...",
  "A faint, rhythmic humming sound begins to resonate, growing louder with each passing second.",
  "Then, without warning, a brilliant shaft of golden light bursts from the cube, piercing the heavens!",
  "It bathes the ruins in its glow for a few fleeting moments before vanishing, leaving only an awe-inspiring memory in its wake.",
  "The cube, now heated and vibrating slightly, lies dormant on the altar.",
  "Suddenly, you hear the unmistakable sound of stone grinding against stone. The altar begins to shift, revealing an underground chamber.",
  "Before the hidden entrance is completely revealed, a distant roar echoes through the air, followed by the rhythmic beating of colossal wings.",
  "A hushed silence descends upon the ruins...",
  "Emerging from the chasm below the cliff's edge, a magnificent golden dragon ascends, landing gracefully among the weathered stones of the ruins.",
  "Its shimmering golden scales catch the sunlight, making the beast seem a creature out of legend.",
  "With an unwavering gaze focused on you, the dragon steps back, drawing itself up to its full majesty as it prepares to attack!",
  "Brace yourself!",
  { race: "dragon", area: "ruins", level: 30 },
  "With a final, resounding blow, the golden dragon crumples to the ground, its strength finally depleted.",
  "Kneeling, you find yourself filled with a mix of triumph and sorrow for the majestic creature's demise.",
  "As you watch, the dragon's body begins to radiate light, its solid form dispersing into millions of twinkling particles that ascend towards the sky, like a cascade of glowing stardust.",
  "With a silent farewell to the fallen beast, you turn your attention back to the hidden entrance.",
  "The underground chamber, now fully revealed, beckons you with its mysteries.",
  "Descending carefully into the revealed room, you find yourself standing before a chest, enveloped in a gentle teal glow.",
  "The question remains: will you open the chest?",
  "transcendent-mithril-chest",
  {
    yes: "Summoning your courage, you approach the chest and gently lift the lid, unveiling its enigmatic contents.",
    no: "Honoring the dragon's memory, you decide not to disturb the chest, opting instead to continue your exploration.",
  },
  "With a final respectful nod towards the resting place of the dragon, you step away from the altar and the chest.",
  "Unfolding your worn map, you consider the numerous paths that lie ahead, marking the next chapter of your grand adventure.",
  "end",
];

export default goldenRuinsStory;
