const howToPlayData = [
  {
    text: "Welcome to the JS Quest 2 tutorial! Click the next button to start your learning journey.",
    imageUrl: "",
  },
  {
    text: "The first thing we need to do is create a character, to do that, click on the 'PLAY FREE' button or navigate to your 'Manage Characters' page in your account.",
    imageUrl: "",
  },
  {
    text: "While in the 'Manage Characters' section, click on the 'CREATE CHARACTER' button.",
    imageUrl: "./create-character.png",
  },
  {
    text: "This will take you to the character creation portal.",
    imageUrl: "./create-character.png",
  },
  {
    text: "First up is selecting your 'Race'. Pick the one you want and then click 'NEXT'.",
    imageUrl: "./select-race.png",
  },
  {
    text: "Next is selecting your 'Class'. Pick the one you want and then click 'NEXT'.",
    imageUrl: "./select-class.png",
  },
  {
    text: "Finally, name your character. Once you have verified all your choices are accurate, click the 'CREATE CHARACTER' button. This will finalize your character and take you back to the 'Manage Characters' page.",
    imageUrl: "./name-character.png",
  },
  {
    text: "From here, click the 'PLAY CHARACTER' button on the character you which to play.",
    imageUrl: "./select-character.png",
  },
  { text: "Now that we are in the game, lets start with the character navigation bar", imageUrl: "" },
  {
    text: "On the left you can see your characters class icon, name, level and arena rank. On the right, it displays your current gold. The center is all the navigation buttons.",
    imageUrl: "./character-info-and-gold.png",
  },
  {
    text: "Defeating enemies will level you up, and progressing through the Arena will increase your arena rank.",
    imageUrl: "./character-info-and-gold.png",
  },
  { text: "First lets look at the map", imageUrl: "./map.png" },
  {
    text: "The map will display all of the locations you can travel to. If the area is 'green', then that means based on your level it should be safe. 'Red' means you migh thave a bit of a struggle.",
    imageUrl: "./pick-region.png",
  },
  {
    text: "The first time you travel to an area, it may take a moment for the area to load. This is due to the time it takes for the magical map to generate the mystical energies to teleport you! (It has nothing to do with the story being generated by ChatGpt).",
    imageUrl: "./pick-region.png",
  },
  {
    text: "The 'Desolate Beach' is one of the starting areas so lets go there!",
    imageUrl: "./pick-region.png",
  },
  {
    text: "When the window pops up, click yes to confirm your travel destination.",
    imageUrl: "./confirm-travel.png",
  },
  {
    text: "If the map 'fizzles out' it's ok, just try again, AI systems aren't perfect and sometimes it produces errors and we wont allow that, so just click travel again.",
    imageUrl: "./confirm-travel.png",
  },
  {
    text: "Once in the area, a story bubble will be at the bottom of your screen, click the next button on the right to continue through your story. Keep in mind, this story is just for you, each story is 100% unique!",
    imageUrl: "./story-progress.png",
  },
  {
    text: "Eventually you will come accross an encounter with an enemy and the game will take you to the battle screen which looks like this.",
    imageUrl: "./battle-screen.png",
  },
  {
    text: "You cannot change your abilities or gear when in this area (we will cover how to do that shortly).",
    imageUrl: "./battle-screen.png",
  },
  {
    text: "To attack the enemy, simply click the ability you wish to use.",
    imageUrl: "./select ability to use.png",
  },
  {
    text: "You will execute your attack, and the enemy will attack back.",
    imageUrl: "./select-ability-to-use.png",
  },
  {
    text: "If the enemy hits you, it will cause damage and take away some of your total health.",
    imageUrl: "./take-damage.png",
  },
  {
    text: "Once you defeat the enemy, a message will pop up tell you how much experience and gold you earned from the fight.",
    imageUrl: "./collect-gold-and-gain-xp.png",
  },
  {
    text: "Continuing on your adventure, you may come accross barrels or chests.",
    imageUrl: "./open-container.png",
  },
  {
    text: "When you find one, be sure to click the 'Open' button.",
    imageUrl: "./open-container.png",
  },
  {
    text: "Doing so, will award you with glorious loot!",
    imageUrl: "./get-loot.png",
  },
  {
    text: "The loot in the land of Pan Strane ranges from the 'Common' to 'Mythical'.",
    imageUrl: "./get-loot.png",
  },
  {
    text: "Once you complete the region, you will be brought back to the map to select the next location to travel.",
    imageUrl: "./pick-region.png",
  },
  {
    text: "This time lets go to a shop and sell some loot and pick up some gear!",
    imageUrl: "./go-to-shop.png",
  },
  {
    text: "Each shop has it's selection of items, consumables, weapons or armor.",
    imageUrl: "./go-to-shop.png",
  },
  {
    text: "Now depending on the race you picked when you made your character will determine the interaction you will have with the shop keep.",
    imageUrl: "./go-to-shop.png",
  },
  {
    text: "Sometimes they arent to happy to see you...",
    imageUrl: "./grumpy-shop.png",
  },
  {
    text: "To sell an item, make sure you are in the sell tab and then select the item you wish to sell.",
    imageUrl: "./sell-item.png",
  },
  {
    text: "With the item card up, click the sell button and get paid!",
    imageUrl: "./get-paid.png",
  },
  {
    text: "Now that we have sold some junk, lets go buy something nice.",
    imageUrl: "./get-paid.png",
  },
  {
    text: "Click on the 'BUY' tab and pick the item you want to purchase.",
    imageUrl: "./buy-item.png",
  },
  {
    text: "With the item card pulled up, click the 'BUY' button and the item will be added to your inventory.",
    imageUrl: "./buy-item.png",
  },
  {
    text: "If you don't have enough gold, to bad guess you'll need to go farm some!",
    imageUrl: "./buy-item.png",
  },
  {
    text: "Lets look at how we might be able to use that item we just bought. Click on the inventory button on the character navigation bar.",
    imageUrl: "./inventory.png",
  },
  {
    text: "Once in your inventory, you can sort based on the category you want and then pick the item you wish to use. (This is not how you equip gear).",
    imageUrl: "./select-potion.png",
  },
  {
    text: "With the item card pulled up, click the use button.",
    imageUrl: "./use-potion.png",
  },
  {
    text: "You will then recover (or heal depending on the item) the amount the potion will restore.",
    imageUrl: "./energy-recover.png",
  },
  {
    text: "Lets look at how we can equip some gear. Click on the character button on the character navigation bar.",
    imageUrl: "./edit-character.png",
  },
  {
    text: "First up is your abilities.",
    imageUrl: "./change-abilities.png",
  },
  {
    text: "When you have more abilities unlocked, you can select which slot you want the ability to fill on your card (basic, primary, secondary).",
    imageUrl: "./change-abilities.png",
  },
  {
    text: "Only 'Basic' abilities can go into the basic slot, but any special ability can go into either the 'Primary' or 'Secondary' slots.",
    imageUrl: "./change-abilities.png",
  },
  {
    text: "It's up to you, but do you think you can find the best combination of abilities?",
    imageUrl: "./change-abilities.png",
  },
  {
    text: "To change your gear, click on the 'Equipment' tab on teh right and then select the item you want to change.",
    imageUrl: "./change-gear.png",
  },
  {
    text: "Here you can see if you have any gear that may be better that what you currently have.",
    imageUrl: "./select-weapon.png",
  },
  {
    text: "Click that item and it will swap out the item you previously had equipped.",
    imageUrl: "./weapon-changed.png",
  },
  {
    text: "Lets take a look at unlocking new skills. Click on the skill tree button in the character navigation bar.",
    imageUrl: "./skill-tree.png",
  },
  {
    text: "Here you can see the two paths you can take to learn skills. Lets take a closer look at one we already have.",
    imageUrl: "./skill-tree.png",
  },
  {
    text: "With the skill card up you can see its description and its effects.",
    imageUrl: "./known-ability.png",
  },
  {
    text: "From left to right you see 'Damage', 'Energy Required', 'Healing Effect', 'Recovery Effect'.",
    imageUrl: "./known-ability.png",
  },
  {
    text: "Now lets look at one we don't have yet.",
    imageUrl: "./unknown-ability.png",
  },
  {
    text: "Looking at this skill you can see that we currently dont have enough skill points to unlock it. To gain more skill points you need to level up!",
    imageUrl: "./not-enough-skill-points.png",
  },
  {
    text: "Looking at this skill you can see that we currently dont have enough skill points to unlock it. To gain more skill points you need to level up!",
    imageUrl: "./not-enough-skill-points.png",
  },
  {
    text: "To exit the game, click on the home button in the character navigation bar.",
    imageUrl: "./exit-game.png",
  },
  {
    text: "Thats the end of the tutorial, now get out there and live your adventure!",
    imageUrl: "",
  },
];

export default howToPlayData;
